### ISSUE TITLE
[HELP] coffee

### ISSUE THREAD

**Issue by kfmgang** [rastapasta/pokemon-go-mitm#133]
hello i have this error 

`ubuntu@ubuntu:~/node_modules/pokemon-go-mitm$ coffee example.logTraffic.coffee
TypeError: 8080.addRequestHandler is not a function
    at Object.<anonymous> (/home/ubuntu/node_modules/pokemon-go-mitm/example.logTraffic.coffee:19:17)
    at Object.<anonymous> (/home/ubuntu/node_modules/pokemon-go-mitm/example.logTraffic.coffee:32:4)
    at Module._compile (module.js:409:26)
    at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:83:25)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:177:29)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
`

help me please

**Comment by jmoriau** [comment]
Have you ever used javascript before? Any programming language at all? Issues are not a support forum. Please close.
