### ISSUE TITLE
npm start fails Error: Module did not self-register

### ISSUE THREAD

**Issue by cryptax** [rastapasta/pokemon-go-mitm#176]
Hello,

When I try npm start, I get this error:
>$ npm start
  pokemon-go-mitm@1.7.0 start /home/axelle/softs/pokemon-go-mitm-node
  coffee example.logTraffic.coffee
Error: Module did not self-register.
  at Error (native)
  at Object.Module._extensions..node (module.js:434:18)
  at Module.load (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at bindings (/home/axelle/softs/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/protobuf.js:9:35)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/axelle/softs/pokemon-go-mitm-node/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
npm ERR! Linux 4.4.0-040400-generic
npm ERR! argv "/opt/node-v4.4.7-linux-x64/bin/node" "/opt/node-v4.4.7-linux-x64/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@1.7.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-go-mitm@1.7.0 start script 'coffee example.logTraffic.coffee'.
npm ERR! This is most likely a problem with the pokemon-go-mitm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee example.logTraffic.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-mitm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pokemon-go-mitm
npm ERR! There is likely additional logging output above.

And there's a debug log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v4.4.7-linux-x64/bin/node',
1 verbose cli   '/opt/node-v4.4.7-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart pokemon-go-mitm@1.7.0
6 info start pokemon-go-mitm@1.7.0
7 verbose unsafe-perm in lifecycle true
8 info pokemon-go-mitm@1.7.0 Failed to exec start script
9 verbose stack Error: pokemon-go-mitm@1.7.0 start: `coffee example.logTraffic.coffee`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/node-v4.4.7-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/node-v4.4.7-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid pokemon-go-mitm@1.7.0
11 verbose cwd /home/axelle/softs/pokemon-go-mitm-node
12 error Linux 4.4.0-040400-generic
13 error argv "/opt/node-v4.4.7-linux-x64/bin/node" "/opt/node-v4.4.7-linux-x64/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error pokemon-go-mitm@1.7.0 start: `coffee example.logTraffic.coffee`
17 error Exit status 1
18 error Failed at the pokemon-go-mitm@1.7.0 start script 'coffee example.logTraffic.coffee'.
18 error This is most likely a problem with the pokemon-go-mitm package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     coffee example.logTraffic.coffee
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs pokemon-go-mitm
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls pokemon-go-mitm
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

My OS is Linux Mint 17.3. I installed nodejs v4.4.7 LTS.
Thanks!

**Comment by rastapasta** [comment]
Please follow the Readme.
**apt-get install libprotobuf-dev**

**Comment by cryptax** [comment]
Hi rastapasta,
it's already installed see below:

> sudo apt-get install libprotobuf-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libprotobuf-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.

I am following your readme step by step. I might have missed something of course. But haven't see what  yet! ;)

**Comment by rastapasta** [comment]
Oh, sorry for being so neglecting in the first place - we got a lot of non-readme reading in the recent time ;) **npm install** ran without problems? could u try starting it directly with **coffee example.logTraffic.coffee**? Cheers and good luck ;)

**Comment by cryptax** [comment]
No problem @rastapasta I understand :)
Actually, I re-installed, and re-started and now it works. I don't know why now, but at least it's working. Perhaps I something to do with the last few pushes you did or not. Anyway it starts now. I'm having problems logging traffic, but I'll investigate more closely first. This issue can be closed for sure.
Thanks.

**Comment by trisk** [comment]
You can just delete `node_modules` to redo `npm install`. Anyway, this can be closed, thanks for the info!

**Comment by cryptax** [comment]
@trisk thanks indeed that's probably a better way to do it.
