### ISSUE TITLE
error logging with example.unknown6.coffee

### ISSUE THREAD

**Issue by FabryB** [rastapasta/pokemon-go-mitm#195]
Using v2.0.0 on linux ubuntu 14.04

/root/pogo/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/protobuf.js:86
    var result = native.parseWithUnknown(buffer, schema, limit, warn, used_typed_array);
                        ^

Error: Malformed protocol buffer
  at Error (native)
  at pb_wrapper.parseWithUnknown (/root/pogo/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/protobuf.js:86:25)
  at /root/pogo/pokemon-go-mitm-node/example.logTraffic.coffee:28:76
  at PokemonGoMITM.handleRequest (/root/pogo/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:203:14)
  at /root/pogo/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:171:37
  at /root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:968:12
  at /root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (/root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (/root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:209:22)
  at [object Object].Proxy._onRequestEnd (/root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:967:9)
  at [object Object].end (/root/pogo/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:804:20)
  at IncomingMessage.onend (_stream_readable.js:498:10)
  at IncomingMessage.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:921:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)

**Comment by FabryB** [comment]
Note: this happens only after some minutes of logging while app is working good. Not doing anything on the app, just open and standing still looking at map with charger and debug function to keep display on while charging

**Comment by trisk** [comment]
I'm not sure what happened to  cause an incorrectly encoded request (connection problems?), but it looks like `protobuf.parse/parseWithUnknown` doesn't catch parsing exceptions in some cases. Will address this.

**Comment by trisk** [comment]
I fixed an uncaught except in `handleResponse` but I don't see any exceptions in `handleRequest` that are not already accounted for, so I'm not really sure how this error is produced.

**Comment by FabryB** [comment]
I think you are referincingyour commit:
https://github.com/rastapasta/pokemon-go-mitm/commit/9cffe6912543a70f34fae27f63c74efd0c863164

Can you please also update example.unknown6.coffee to use your new function?

**Comment by FabryB** [comment]
I made it run for over an hour with your modification, no crash.
No errors either, but I think I need to run in debug mode to see them ?

**Comment by trisk** [comment]
Yeah, I see the problem in `example.unknown6.coffee` now. Let me know if this works:
```diff
--- a/example.unknown6.coffee
+++ b/example.unknown6.coffee
@@ -15,5 +15,5 @@ pcrypt = require 'pcrypt'
 server = new PokemonGoMITM port: 8081
        .addRequestEnvelopeHandler (data) ->
                buffer = pcrypt.decrypt data.unknown6?.unknown2?.encrypted_signature
-               console.log POGOProtos.parseWithUnknown buffer, 'POGOProtos.Networking.Envelopes.Signature'
+               console.log this.parseProtobuf buffer, 'POGOProtos.Networking.Envelopes.Signature'
                false
```

**Comment by FabryB** [comment]
I have modified the base logTraffic simply adding this:

`        .addRequestEnvelopeHandler (data) ->
                console.log  new Date().toJSON(), " [->] Envelope Signature", JSON.stringify(data, null, 4), "\n"
                false`

And it works!

**Comment by trisk** [comment]
That prints the envelope, but doesn't show the signature, which is encrypted.

**Comment by trisk** [comment]
Fixed in current `example.logTrafficFull.coffee` (unknown6-only example will be deleted).
