### ISSUE TITLE
Cant start Error: Module did not self-register.

### ISSUE THREAD

**Issue by Jimmy062006** [rastapasta/pokemon-go-mitm#217]
(node:23987) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
Error: Module did not self-register.
  at Error (native)
  at Object.Module._extensions..node (module.js:583:18)
  at Module.load (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at bindings (/home/test1/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_mod
es/bindings/bindings.js:76:44)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobu
protobuf.js:9:35)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:16:
)
  at Module.load (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/coffee-scrip
js:134:23)
  at compileScript (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:224:29
  at compilePath (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:9
20)
  at Object.<anonymous> (/home/test1/pokemon-go-mitm-node/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

**Comment by trisk** [comment]
Either failed to build dependencies or using an outdated version of Node (4.0.0 is the minimum)

**Comment by Jimmy062006** [comment]
npm ERR! Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@2.1.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1

Hmm it seemed to build ok

**Comment by trisk** [comment]
`/usr/local/bin/iojs` in your command is suspicious. io.js is an obsolete fork of Node.js and there's probably some incompatibility there; try reinstalling a recent version of Node (and delete `node_modules` directory before doing `npm install` again).
