### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by nogard230** [rastapasta/pokemon-go-mitm#219]
i can't run, some tips?
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.37
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@2.1.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-go-mitm@2.1.0 start script 'coffee example.logTraffic.coffee'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-go-mitm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee example.logTraffic.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-mitm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-go-mitm
npm ERR! There is likely additional logging output above.

**Comment by nogard230** [comment]
On coffee:
coffee example.logTraffic.coffee 

/home/adriana/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/middleware/wildcard.js:8
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:24:27)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/node_modules/http-mitm-proxy/index.js:3:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/adriana/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:456:26)

**Comment by rastapasta** [comment]
npm ERR! node v0.10.37
npm ERR! npm v3.10.6

you have to use node >= 4 - Cheers! 🍺

**Comment by nogard230** [comment]
thanks
