### ISSUE TITLE
Coffee issue.

### ISSUE THREAD

**Issue by Gatopaint** [rastapasta/pokemon-go-mitm#226]
I came with a error, i reset the terminal because i accidentally used sudo. 

I tried it all over again and this is the error:

`gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ coffee example.logTraffic.coffee
Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:455:15)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

`

Any suggestions?

**Comment by trisk** [comment]
You probably forgot to `npm install`

**Comment by Gatopaint** [comment]
@Trisk Its doing something. I was almost say it was going to work. 
`gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ coffee example.logTraffic.coffee
Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:455:15)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3`

**Comment by Gatopaint** [comment]
I use Ctrl C too much x-x 
Its this:
`gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ npm install
npm WARN checkPermissions Missing write access to /home/gatopaint/pokemon-go-mitm-node/node_modules
pokemon-go-mitm@2.1.0 /home/gatopaint/pokemon-go-mitm-node
├── bluebird@3.4.6 
├─┬ change-case@3.0.0 
│ ├── camel-case@3.0.0 
│ ├── constant-case@2.0.0 
│ ├── dot-case@2.1.0 
│ ├── header-case@1.0.0 
│ ├── is-lower-case@1.1.3 
│ ├── is-upper-case@1.1.2 
│ ├── lower-case@1.1.3 
│ ├── lower-case-first@1.0.2 
│ ├── no-case@2.3.0 
│ ├── param-case@2.1.0 
│ ├── pascal-case@2.0.0 
│ ├── path-case@2.1.0 
│ ├── sentence-case@2.1.0 
│ ├── snake-case@2.1.0 
│ ├── swap-case@1.1.2 
│ ├── title-case@2.1.0 
│ ├── upper-case@1.1.3 
│ └── upper-case-first@1.1.2 
├── geodesy@1.1.1 
├─┬ http-mitm-proxy@0.5.1  (git+https://github.com/joeferner/node-http-mitm-proxy.git#a6f8469401616cec13c3f16f685021a33df7e0df)
│ ├── async@1.5.2 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ optimist@0.6.1 
│ │ └── wordwrap@0.0.3 
│ ├── semaphore@1.0.5 
│ └─┬ ws@1.1.1 
│   ├── options@0.0.6 
│   └── ultron@1.0.2 
├── lodash@4.15.0 
├── moment@2.14.1 
├── node-forge@0.6.42 
├── pcrypt@1.0.0  (git+https://github.com/laverdet/pcrypt.git#1202a0df9072182418754c0462264bde01818900)
├─┬ pokemongo-protobuf@1.12.0 
│ └─┬ node-protobuf@1.3.3 
│   ├── bindings@1.2.1 
│   └── nan@2.4.0 
├─┬ raw-body@2.1.7 
│ ├── bytes@2.4.0 
│ ├── iconv-lite@0.4.13 
│ └── unpipe@1.0.0 
├─┬ request@2.74.0 
│ ├── aws-sign2@0.6.0 
│ ├── aws4@1.4.1 
│ ├─┬ bl@1.1.2 
│ │ └─┬ readable-stream@2.0.6 
│ │   ├── core-util-is@1.0.2 
│ │   ├── inherits@2.0.1 
│ │   ├── isarray@1.0.0 
│ │   ├── process-nextick-args@1.0.7 
│ │   ├── string_decoder@0.10.31 
│ │   └── util-deprecate@1.0.2 
│ ├── caseless@0.11.0 
│ ├─┬ combined-stream@1.0.5 
│ │ └── delayed-stream@1.0.0 
│ ├── extend@3.0.0 
│ ├── forever-agent@0.6.1 
│ ├─┬ form-data@1.0.1 
│ │ └── async@2.0.1 
│ ├─┬ har-validator@2.0.6 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.0.0 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├─┬ is-my-json-valid@2.13.1 
│ │ │ ├── generate-function@2.0.0 
│ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ └── is-property@1.0.2 
│ │ │ ├── jsonpointer@2.0.0 
│ │ │ └── xtend@4.0.1 
│ │ └─┬ pinkie-promise@2.0.1 
│ │   └── pinkie@2.0.4 
│ ├─┬ hawk@3.1.3 
│ │ ├── boom@2.10.1 
│ │ ├── cryptiles@2.0.5 
│ │ ├── hoek@2.16.3 
│ │ └── sntp@1.0.9 
│ ├─┬ http-signature@1.1.1 
│ │ ├── assert-plus@0.2.0 
│ │ ├─┬ jsprim@1.3.0 
│ │ │ ├── extsprintf@1.0.2 
│ │ │ ├── json-schema@0.2.2 
│ │ │ └── verror@1.3.6 
│ │ └─┬ sshpk@1.10.0 
│ │   ├── asn1@0.2.3 
│ │   ├── assert-plus@1.0.0 
│ │   ├─┬ bcrypt-pbkdf@1.0.0 
│ │   │ └── tweetnacl@0.14.3 
│ │   ├─┬ dashdash@1.14.0 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── ecc-jsbn@0.1.1 
│ │   ├─┬ getpass@0.1.6 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── jodid25519@1.0.2 
│ │   ├── jsbn@0.1.0 
│ │   └── tweetnacl@0.13.3 
│ ├── is-typedarray@1.0.0 
│ ├── isstream@0.1.2 
│ ├── json-stringify-safe@5.0.1 
│ ├─┬ mime-types@2.1.11 
│ │ └── mime-db@1.23.0 
│ ├── node-uuid@1.4.7 
│ ├── oauth-sign@0.8.2 
│ ├── qs@6.2.1 
│ ├── stringstream@0.0.5 
│ ├── tough-cookie@2.3.1 
│ └── tunnel-agent@0.4.3 
└─┬ request-promise@4.1.1 
  ├── request-promise-core@1.1.1 
  └── stealthy-require@1.0.0 

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! path /home/gatopaint/pokemon-go-mitm-node/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/gatopaint/pokemon-go-mitm-node/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/home/gatopaint/pokemon-go-mitm-node/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/gatopaint/pokemon-go-mitm-node/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gatopaint/pokemon-go-mitm-node/npm-debug.log
`

**Comment by Gatopaint** [comment]
Nevermind i did need to use sudo! got the certificate!

**Comment by Gatopaint** [comment]
ummm... More help kitty? @trisk 

gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ coffee example.logTraffic.coffee
[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate

**Comment by trisk** [comment]
Try reading the instructions

**Comment by trisk** [comment]
And the only reason you had that error earlier is because you messed up the directory permissions  by using `sudo` for no reason. I recommend deleting the directory and starting over.

**Comment by trisk** [comment]
And since you are using virtualbox you have to make sure the network settings will let you connect to the VM from outside.

**Comment by gwarfan07** [comment]
hello im using unbutu everytime i run coffee example.logTraffic.coffee i get this error  "/usr/bin/env: 'node' : no such file or directory"
how do i fix?

**Comment by jmoriau** [comment]
@gwarfan07 **sigh** I'm sorry but if you can't fix this you probably can't use this project._

**Comment by gwarfan07** [comment]
why is that?

**Comment by gwarfan07** [comment]
i dont have that path

**Comment by gwarfan07** [comment]
i fixed it you have to run command sudo ln -s /usr/bin/nodejs /usr/bin/node then run coffee example.logTraffic.coffee then run npm install and then run coffee example.logTraffic.coffee and it will work
