### ISSUE TITLE
help me when the people press the button transfer pokemon this happen

### ISSUE THREAD

**Issue by RBOY2017** [rastapasta/pokemon-go-mitm#236]
[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[-] RequestError: Error: Argument error, options.body.
[-] RequestError: Error: Argument error, options.body.
[-] RequestError: Error: Argument error, options.body.
[-] RequestError: Error: Argument error, options.body.
[-] RequestError: Error: Argument error, options.body.
C:\Users\rboy\Downloads\pokemon-go-mitm-node\example.logTraffic.coffee:31
        if (pokemon = item.inventory_item_data.pokemon_data) {
                                              ^

TypeError: Cannot read property 'pokemon_data' of undefined
  at PokemonGoMITM.<anonymous> (C:\Users\rboy\Downloads\pokemon-go-mitm-node\example.logTraffic.coffee:25:42)
  at PokemonGoMITM.handleResponseAction (C:\Users\rboy\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:440:9)
  at PokemonGoMITM.handleResponse (C:\Users\rboy\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:343:26)
  at C:\Users\rboy\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:243:17
  at C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:1010:12
  at C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:181:20
  at Object.async.forEachOf.async.eachOf (C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:233:13)
  at Object.async.forEach.async.each (C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:209:22)
  at Proxy._onResponseEnd (C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:1009:9)
  at ProxyFinalResponseFilter.end (C:\Users\rboy\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:846:20)
  at Gunzip.onend (_stream_readable.js:511:10)
  at Gunzip.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Gunzip.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by trisk** [comment]
Your script is assuming every item has the `inventory_item_data` field. You should make your loop conditional on `when item.inventory_item_data`.
